import { BehaviorSubject, Observable, of } from 'rxjs';
import { HttpClient } from "@angular/common/http";
import { Injectable } from "@angular/core";

export const PAGE_LIMIT = 6;

@Injectable()
export class OwnVarietiesService {

  PAGE_LIMIT = 6;

  private currentPage$: BehaviorSubject<number> = new BehaviorSubject<number>(1);

  // TEMPORARY
  mockedItems: OwnVarietiesItemModel[] = [
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-1.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
    { url: '/assets/images/own-varieties-gallery-2.jpg', title: 'Leucothoe fontanesiana “Makijaż”', desc: 'Zimozielony, niski, dobrze zagęszczający się krzew o wielobarwnych, marmurkowo-pstrych liściach. Wiosną przebarwienia mają kolor kremowo-zielony, latem pojawia się barwa czerwono-różowa, a jesienią i zimą przeważają odcienie bordo. Kwitnie w maju, kwiaty są białe, dzwoneczkowate, zebrane w grona. Po 10 latach dorasta do około 0.5m wysokości i około 0,8m szerokości. Wymaga gleb lekkich i kwaśnych, oraz słonecznego stanowiska, nie wymaga cięcia. Doskonały do nasadzeń pojedynczych, jak i w połączeniu z wrzosami, azaliami, różanecznikami, a również niskimi bylinami. Roślina chroniona prawem własności EU 30742, JP 28957' },
  ];

  constructor(private http: HttpClient) {}

  getPaginated(pageIndex: number): Observable<OwnVarietiesItemModel[]> {
    const skip = pageIndex * PAGE_LIMIT;
    // return this.http.get<OwnVarietiesItemModel>(`GET_OWN_VARIETIES_URL`, { payload });
    const toReturn = [...this.mockedItems].slice(skip, skip + 6);
    return of(toReturn);
  }

  setCurrentPage(page: number): void {
    this.currentPage$.next(page);
  }

  getCurrentPage(): Observable<number> {
    return this.currentPage$.asObservable();
  }

}

export interface OwnVarietiesItemModel {
  url: string;
  title: string;
  desc: string;
}